### ISSUE TITLE
about clearAll function

### ISSUE THREAD

**Issue by lei-zhu** [timfpark/react-native-cache#9]
your [clearAll] function is remove all [AsyncStorage] items，but i want remove cache items only specified by namespace when call the [clearAll] function. Can you provide the this function ?

在使用 react-native-cache 的时候，调用 clearAll 方法会删除所有存储在 AsyncStorage 中的数据。但我认为，只应该删除当前指定命名空间的缓存数据。您能修改一下吗？

**Comment by mcrowe** [comment]
@timfpark It seems very dangerous to keep the `clearAll` functionality as is. It will clear all keys in AsyncStorage instead of just those in the namespace. This will inevitably cause irreparable damage to some unsuspecting app using this library. I would strongly recommend either documenting the bug, fixing it, or unpublishing this library from npm.

**Comment by timfpark** [comment]
Thanks for reporting - fixed in version 1.1.3
